### PR TITLE
[Feature Request] App Shortcuts and Circular Icon for Android 7.1+

### PR DESCRIPTION
**Pull request by rodrigoswz**
Hi, please add **App Shortcuts** for quick acess catalog of TV Shows, Movies or Anime. Very useful!

More info about this feature: https://developer.android.com/preview/shortcuts.html

Another nice feature of Android 7.1 is **Circular Icon** for _Google Pixel_ devices or any others that supports it to match all other applications.

More info about Circular Icon here: http://android-developers.blogspot.com.br/2016/10/android71-dev-preview-available.html

### CODE REVIEW

**Comment by xaiki** [comment]
@vzamanillo @ChrisAlderson anything we want to port from this ?

**Comment by vzamanillo** [comment]
I am actually doing the merge for dagger, the next step will be the okhttp, then we could do it.

**Comment by xaiki** [comment]
dagger and okhttp have been merged here, haven't they ?

**Comment by vzamanillo** [comment]
#76

**Comment by xaiki** [comment]
are there still things here we want ?

**Comment by blazsolar** [comment]
Can we close this. If anything from popcorn should be added to butter it should be cherry picked. Merging whole develop branch is not an option.

**Comment by aldoborrero** [comment]
Yup, close this one. This feature should be discussed and added (if necessary) when we revamp media providers.

**Comment by xaiki** [comment]
feel free to close, you guys are now my android overlords

**Pull request closed without merging**
