### PR TITLE
Moving terms screen to MVP

### PR DESCRIPTION
**Pull request by blazsolar**

### CODE REVIEW

**Comment by xaiki** [comment]
@vzamanillo ?

**Comment by xaiki** [comment]
looks like previous merge broke this one.

**Comment by blazsolar** [comment]
should be ok now

**Comment by vzamanillo** [comment]
I did not test it, but looks ok and ready to merge.

**Comment by xaiki** [comment]
@vzamanillo you too can merge !!

**Comment by vzamanillo** [comment]
Hehehe, I know, sorry

**Pull request merged**
