### PR TITLE
Modifiying checkstyle rules

### PR DESCRIPTION
**Pull request by blazsolar**
Slightly modifying checkstyle configuration. 
Checkstyle rules violations will now fail build on CI.
Setting max error count so we don't have to fix all the violations immediately.

### CODE REVIEW

**Comment by aldoborrero** [comment]
Good one @blazsolar :)

**Comment by xaiki** [comment]
looks like this closes #133 and is ready to go in ?

**Comment by blazsolar** [comment]
Some minor changes are still required

**Comment by aldoborrero** [comment]
When done @blazsolar ping me and I'll review

**Comment by blazsolar** [comment]
This PR is now for review. We have a solid base now for code styles but I assume there will still be some minor changes during the course of development.

**Comment by blazsolar** [comment]
@aldoborrero Can you review please?

**Comment by aldoborrero** [comment]
Are those checkstyle changes included in the intellij-java-butter-style.xml file?

**Comment by blazsolar** [comment]
yes they are

**Pull request merged**
