### PR TITLE
Preferences updates

### PR DESCRIPTION
**Pull request by aldoborrero**
- Removed Changelog section (it was not used  properly and when trying to use the library doesn't load properly the xml)
- Added clipToPadding to false to avoid having a bad margin in the RecyclerView
- Changed the library to pick and select the folder for the cache

### CODE REVIEW

**Comment by blazsolar** [comment]
Why was change log removed?

**Comment by aldoborrero** [comment]
Restored changelog lib working properly on TV and Mobile.

I have to fix a couple of things on TV that are related to opening a Webview, don't merge yet until further notice!

**Comment by aldoborrero** [comment]
@blazsolar Review these changes and if you feel that everything is OK merge it! 👍

**Comment by blazsolar** [comment]
can you check what is happening with ci

**Pull request merged**
